config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  get "flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :get_flats, only: [:index, :show]

  def index
  end

  def show
    @flat = @flats.find { |flat| flat["id"] == params[:id].to_i }
  end

  private

  def get_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<% @flats.each do |flat| %>

    <div class="card" style="position: relative;">
      <h3> <%= flat["name"] %> </h3>
      <%= image_tag flat["imageUrl"], alt: "alttext", width: "200px" %>
      <p><%= flat["price"]%> <%=  flat["priceCurrency"] %></p>
      <p>Lat: <%= flat["lat"] %></p>
      <p>Lng: <%= flat["lng"] %></p>
     <%= link_to flat_path(flat['id']) do %>
        See more
     <% end %>
    </div>
<% end %>
<p>Find me in app/views/flats/index.html.erb</p>

app/views/flats/show.html.erb
<h1> <%= @flat["name"] %> </h1>
<%= image_tag @flat["imageUrl"], alt: "alttext", width: "200px" %>
<p><%= @flat["price"]%> <%=  @flat["priceCurrency"] %></p>
<p>Lat: <%= @flat["lat"] %></p>
<p>Lng: <%= @flat["lng"] %></p>

<%= link_to "Go back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb310</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>